config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admins do
    get 'contacts/index'
    get 'contacts/:id/show' => 'contacts#show', as: 'contact_show'
    get 'contacts/new'
    post 'contacts' => 'contacts#create'

   # get 'users/show'
   #get 'users/index' => 'admins/users#index'
   # get 'users/edit'
   # get 'users/update'
   # delete 'users/destroy'
   post 'users/:id/edit' => 'admins/users#edit', as: 'edit_user'
   resources :users, only:[:show, :index, :edit, :update, :destroy]
   get 'users/search', to: 'users#search', as: 'search_user'
  end

  namespace :admins do
    get 'products/new' => 'products#new', as: 'new_product'
    post 'products/new' => 'products#new', as: 'create_product'
    resources :products, only: [:index, :show, :destroy, :edit]
  end

  namespace :admins do
    get 'orders/index'
    get 'orders/:id/show' => 'orders#show', as: 'order_show'
    patch 'orders/:id/update' => 'orders#update', as: 'order_update'
    patch 'orders/:id/update2' => 'orders#update2', as: 'order_update2'
  end



  resources :users, only: [:edit, :update, :destroy]
  get 'users/top' => 'users#top'
  get 'users/:id/password_confirmation' => 'users#confirm', as: 'confirm_user'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/:id/edit_name' => 'users#edit_name', as: 'edit_name_user'
  get 'users/:id/edit_address' => 'users#edit_address', as: 'edit_address_user'
  get 'users/:id/edit_phonenumber' => 'users#edit_phonenumber', as: 'edit_phonenumber_user'
  get 'users/:id/edit_email' => 'users#edit_email', as: 'edit_email_user'
  get 'users/:id/edit_password' => 'users#edit_password', as: 'edit_password_user'



  #get 'favorites/create'
  #get 'favorites/destroy'
  resources :contacts, only: [:new, :create]
  # get '/contacts/new' => 'contacts#new'
  # post '/contacts/create' => 'contacts#create'


  resources :orders, only: [:new, :show, :create] do
    collection do
      post 'confirm'
      post 'confirm_user'
    end
  end
  # get 'orders/new' => 'orders#new'
  # post 'orders/create_address' => 'orders#create_address'
  # post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  # post 'orders/create' => 'orders#create', as:'create_order'
  # get 'orders/show' => 'orders#show', as: 'show_order'

  #get 'carts/add_cart_item' => 'carts#add_cart_item'
  post '/products/:id/add_cart_items' => 'products#add_cart_item', as: 'add_cart_items'
  get '/products/bpms' => 'products#bpms', as: 'bpms-products'

  resources :carts, only: [:index, :destroy] do
    resource :cart_items, only: [:update]
    resources :cart_items, only: [:destroy]
  end
  # get 'carts/:id' => 'carts#show', as: 'carts_show'
  # delete 'carts/delete_item' => 'carts#delete_item', as: 'delete_cart_item'
  # delete 'carts/delete_all_items' => 'carts#delete_all_items', as: 'delete_all_cart_items'

  #get 'products/index'
  #get 'products/show'
  patch 'products/:id/update' => 'products#update', as: 'update_product'
  resources :products, only: [:index, :show] do
    resource :favorites, only:[:create, :destroy]
  end

  get 'admins/top' => 'admins/users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resourses :contacts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_paranoid

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at? super: :deleted_account
  end

# gem jp_prefectureの追加の為、追記しました------------------------------------------------
  include JpPrefecture
  jp_prefecture :pref

    def prefecture_name
      JpPrefecture::Prefecture.find(code: pref_id).try(:name)
    end

    def prefecture_name=(prefecture_name)
      self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture_name).code
    end

# ----------------------------------------------------------------------------------

  has_many :orders
  has_many :addresses
  has_one :cart
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :orders, :allow_destroy => true
  has_many :order_items, through: :orders  #ユーザーマイページの購入履歴表示に必要

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,
  	presence:true,
  	length: { minimum: 1, maximum: 20}

  validates :last_name,
  	presence:true,
  	length: { minimum: 1, maximum: 20}

  validates :kana_first,
  	presence:true,
    format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  validates :kana_last,
  	presence:true,
    format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  validates :postal_code,
  	presence:true

  validates :pref,
  	presence:true

  validates :city,
  	presence:true

  validates :phone_number,
  	presence:true,
    format: { with: /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/,
            message: 'は正しい電話番号で入力して下さい。 例：◯◯◯-◯◯◯◯-◯◯◯◯ 、「ー」は無しでも可' }
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @o_counter = Order.count
    @u_counter = User.count
    @p_counter = Product.count
    # 注文直近１０件をひっぱってくる記述

    @q = Order.ransack(params[:q])
    @orders2 = @q.result.last(10)
    if @q == nil
      @msg = "現在注文はありません"
    end
    # ユーザー直近１０件の登録者を表示
    @q2 = User.ransack(params[:q])
    @users2 = @q2.result.last(10)
    if @users2 == nil
      @msg2 = "現在登録ユーザーはいません"
    end
    # binding.pry
    # @admin = Admin.find(params[:id])
  end

  def index
    @users2 = User.all
    @users = User.with_deleted.page(params[:page]).per(30)
    @admins = Admin.all

    @q = User.ransack(params[:q])
    @searchuser = @q.result
    @q2 = User.with_deleted.ransack(params[:q])
    @searchuser2 = @q2.result
  end

  def search
    @q = User.search(search_params)
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.with_deleted.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '登録情報を更新しました！'
      redirect_to admins_user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.soft_delete
      flash[:success] = 'ユーザーを削除しました(soft_deleted)'
      render 'index'
    end
  end

private
  def user_params
    params.require(:user).permit(:first_name,
                                  :last_name,
                                  :kana_first,
                                  :kana_last,
                                  :postal_code,
                                  :pref,
                                  :city,
                                  :address1,
                                  :address2,
                                  :phone_number,
                                  :email,
                                  :password)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected
  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |user|
    end
    @cart = Cart.new
    if current_user
       @cart.user_id = current_user.id
       @cart.save
    end
  end

  # GET /resource/edit
  def edit
    #super do
    #end
    @user = current_user
    @orders = @user.orders.find_by(status: '0')
    @orders2 = @user.orders.find_by(status: '1')
  end

  # PUT /resource
  # def update
    # super
    # end
    # @user = current_user
    # if @user.id == current_user.id
    #     # redirect_to edit_user_password_path(current_user)
    #   # redirect_to edit_user_path(current_user)

    #   render :edit_password
    # else
    #   redirect_to edit_user_path(current_user)
    # end
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    edit_user_path(current_user)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top]

  def top
    @users = User.last(10)
    @orders = Order.last(10)
    @q = Product.includes(:discs,:musics).ransack(params[:q])
  end

  def confirm
  end

  def mypage
    @user = User.find(params[:id])
    @favorites = @user.favorites.reverse_order
    @q = Product.includes(:discs,:musics).ransack(params[:q])
    @q2 = Music.ransack(params[:q])
    @msg = 'お気に入りリストに商品は入っておりません。'
    @msg2 = '購入履歴はございません。'
  end

  def edit
    @q = Product.includes(:discs,:musics).ransack(params[:q])
    @q2 = Music.ransack(params[:q])
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_name
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_name
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_address
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_address
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_phonenumber
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_phonenumber
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_email
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_email
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_password
    # @user = User.find(params[:id])
    @user = current_user
    if @user.id == current_user.id
      # redirect_to edit_password_user_path(current_user)
      # render :edit_password
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'successfully updated'
      redirect_to edit_user_path(@user.id)
    else
      redirect_to edit_user_path(@user.id)
    end
  end

  def destroy
    @user = current_user
    @user.soft_delete
    sign_out(@user)
  end

  private
    def user_params
      params.require(:user).permit(:email,:encrypted_password,:first_name,:last_name,:kana_first,:kana_last,:postal_code,:pref,:city,:address1,:address2,:phone_number)
    end


end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<h1>Users#confirm</h1>
<p>Find me in app/views/users/confirm.html.erb</p>

app/views/users/edit.html.erb
<!-- headerの部分テンプレート -->
  <%= render 'layouts/user_header'  %>
<!-- main-visual -->
<!-- 検索フォーム -->
  <%= render 'products/list', q: @q, q2: @q2 %>
<!--             -->

<div class="user-inverse" style="padding-top:40px;">
<div class="users-edit-box">
    <div class="">
    	<i class="fa fa-sign-in"></i>
    </div>
		<p class="users-edit-title">登録情報の編集</p>
  <div class="users-edit-boxes">
		<p class="users-edit-information-name">
			<label>名前：</label>
			<label><%= @user.first_name %><%= @user.last_name %></label>
    </p>
    <p class="users-edit-information">
      <label class="users-edit-information-contents">
        <label>カナ：</label>
        <%= @user.kana_first %><%= @user.kana_last %>
      </label>
      <%= link_to edit_name_user_path(@user.id) do %>
        <button type="button" class="users-edits-button-style" >編集</button>
      <% end %>
		</p>
    <p class="users-edit-information">
      <label class="users-edit-information-contents">
        <label>住所：</label>
        <%= @user.postal_code %><br>
        <%= @user.pref %> <%= @user.city %>
        <%= @user.address1 %> <%= @user.address2 %>
      </label>
      <%= link_to edit_address_user_path(@user.id) do %>
        <button type="button" class="users-edits-button-style" >編集</button>
      <% end %>
    </p>
    <p class="users-edit-information">
      <label class="users-edit-information-contents">
        <label>電話番号：</label>
        <%= @user.phone_number %>
      </label>
      <%= link_to edit_phonenumber_user_path(@user.id)  do %>
        <button type="button" class="users-edits-button-style" >編集</button>
      <% end %>
    </p>
    <p class="users-edit-information">
      <label class="users-edit-information-contents">
        <label>メールアドレス：</label>
        <%= @user.email %>
      </label>
      <%= link_to edit_email_user_path(@user.id)  do %>
        <button type="button" class="users-edits-button-style" >編集</button>
      <% end %>
    </p>
    <p class="users-edit-information">
      <label class="users-edit-information-contents">
        <label>パスワード</label>
      </label>
      <%= link_to edit_password_user_path(@user.id) do %>
        <button type="button" class="users-edits-button-style" >編集</button>
      <% end %>
    </p>
    <p><%= link_to "終了(ホームへ)", products_path, class: "end-home-button-style" %> | <%= link_to "退会する", edit_user_registration_path, class: "unsubscribe-button-style" %></p>
  </div>
</div>
</div>

app/views/users/edit_address.html.erb
<!-- headerの部分テンプレート -->
  <%= render 'layouts/user_header'  %>
<!-- main-visual -->

<div class="users-edit-page user-inverse">
    <div class="users-edit-show-boxes">
    	<div class="mail-icon">
		    <div class="">
		    	<i class="fa fa-sign-in"></i>
		    </div>
			<p class="users-edit-title">住所の変更</p>
	  	</div>
    	<%= form_for(@user) do |f| %>
			<div class="users-edit-show-informations">
				<label>郵便番号</label>
				<p><%= f.text_field :postal_code, class: "uses_edit-show-info col-xs-3", :placeholder => "郵便番号" %></p>
	    	</div>
	    	<div class="users-edit-show-informations-pref">
	    		<label>都道府県</label>
	    		<p class="users_edit-show-prefecture"><%= f.collection_select :pref, JpPrefecture::Prefecture.all, :name, :name%></p>
	    	</div>
	    	<div class="users-edit-show-informations">
	    		<label>市町村</label>
	    		<p><%= f.text_field :city, class: "uses_edit-show-info col-xs-8", :placeholder => "市町村" %></p>
	    	</div>
	    	<div class="users-edit-show-informations">
	    		<label>番地</label>
	    		<p><%= f.text_field :address1, class: "uses_edit-show-info col-xs-5", :placeholder => "番地" %></p>
	    	</div>
	    	<div class="users-edit-show-informations">
	    		<label>建物名/部屋番号</label>
			    <p><%= f.text_field :address2, class: "uses_edit-show-info col-xs-8", :placeholder => "建物名/部屋番号" %></p>
	    	</div>
	    	<div class="actions-users-edit-show-box">
			<%= f.submit "変更内容を保存", class: "actions-users-edit-show" %>
			<%= link_to "戻る", edit_user_path(@user.id),class: "actions-users-edit-show-back" %>
			</div>
		<% end %>
    </div>
</div>

app/views/users/edit_email.html.erb
<!-- headerの部分テンプレート -->
  <%= render 'layouts/user_header'  %>
<!-- main-visual -->

<div class="users-edit-page user-inverse">
    <div class="users-edit-show-boxes">
    	<div class="mail-icon">
		    <div class="">
		    	<i class="fa fa-sign-in"></i>
		    </div>
			<p class="users-edit-title">メールアドレスの変更</p>
  		</div>
    	<%= form_for(@user) do |f| %>
			<div class="users-edit-show-informations">
				<label>現在のメールアドレス</label><br>
				<div>
					<div class="users_edit-show-current-phonenumber-email-box"><%= @user.email %></div>
				</div>
	    	</div>
	    	<div class="users-edit-show-informations">
	    		<label>新しいメールアドレス</label>
	    		<p><%= f.text_field :email, class: "uses_edit-show-info col-xs-5", :placeholder => "メールアドレス" %>
	    	</div>
	    	<div class="actions-users-edit-show-box">
			<%= f.submit "変更内容を保存", class: "actions-users-edit-show" %>
			<%= link_to "戻る", edit_user_path(@user.id),class: "actions-users-edit-show-back" %>
			</div>
		<% end %>
    </div>
</div>

app/views/users/edit_password.html.erb
<%= render 'layouts/user_header' %>
<section class="main-box user-inverse" style="padding-top:40px;">
  <p class="page-title">パスワードの変更</p>
  <div class="contents-box">
    <div class="field-box">
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>

        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
        <% end %>

        <div class="field">
          <%= f.label :現在のパスワード %><br/>
          <%= f.password_field :current_password, autocomplete: "current-password", class: "form-control", style: "background-color:transparent;" %>
        </div>

        <div class="field">
          <%= f.label :新しいパスワード %><br/>
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control", style: "background-color:transparent;", placeholder: "８文字以上" %>
          <% if @minimum_password_length %>
            <br />
            <em><%= @minimum_password_length %> characters minimum</em>
          <% end %>
        </div>

        <div class="field">
          <%= f.label :パスワード再入力 %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", style: "background-color:transparent;", placeholder: "８文字以上" %>
        </div>

        <div class="actions">
          <div align="right" style="padding-top:10px;">
            <%= f.submit "変更内容を保存", class: "btn-lg users-edits-button-style" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/mypage.html.erb
<!-- headerの部分テンプレート -->
  <%= render 'layouts/user_header'  %>
<!-- main-visual -->
<!-- 検索フォーム -->
  <%= render 'products/list', q: @q, q2: @q2 %>
<!--             -->

<div class="users-mypage user-inverse">
  <div class="users-mypage-main-box">
    <div class="users-favorites-info-box">
      <div class="users-info-box">
        <p class="users-info">登録情報</p>
        <p class="current-user"><label>名前：</label><%= @user.first_name %> <%= @user.last_name %></p>
        <p class="current-user"><label>郵便番号：</label><%= @user.postal_code %></p>
        <p class="current-user"><label>住所：</label><%= @user.pref + @user.city %><%= @user.address1 %> <%= @user.address2 %></p>
        <p class="current-user"><label>電話番号：</label><%= @user.phone_number %></p>
        <p class="current-user"><label>メールアドレス：</label><%= @user.email %></p>
        <%= link_to edit_user_path(@user.id) do %>
          <button type="button" class="edit-button-style" >登録内容編集</button>
        <% end %>
      </div>
      <div class="favorites-info-box">
        <p class="favorites-info">お気に入りリスト</p>
        <div class="favorites-all-contents">
          <% if @favorites.any? %>
            <% @favorites.each do |favorite| %>
              <div class="favorites-contents">
                <%= link_to product_path(favorite.product.id) do %>
                  <div class="favorites-product-image">
                    <%= attachment_image_tag favorite.product, :image, :fill, 150, 150, fallback: 'icon-mypage.png', :size => "150x150" %>
                  </div>
                <% end %>
                <div class="favorites-product-info-box">
                  <p class="favorites-product-info"><label>アルバム/シングル名：</label><%= favorite.product.album_title %></p>
                  <p class="favorites-product-info"><label>アーティスト名：</label><%= favorite.product.artist  %></p>
                  <%= link_to product_favorites_path(favorite.product_id), method: :delete do %>
                    <button type="button" class="favorites-destroy-button-style" >お気に入りから外す</button>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>
            <p class="favorite-nothing-message"><%= @msg %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="orders-info-box">
      <p class="orders-info">購入履歴</p>
      <div class="orders-all-contents">
        <% if @user.orders.any? %>
          <% @user.orders.reverse_each do |order| %>
            <div class="orders-contents">
              <table class="table">
                <thead>
                  <tr>
                    <th>購入日： <%= order.created_at.strftime('%Y年%m月%d日') %></th>
                    <th>ステータス： <%= order.status %></th>
                    <th>合計金額： ￥<%= order.total %></th>
                  </tr>
                </thead>
              </table>
              <p class="orders-address">
                <label>送付先：</label>
                <span><%= order.address.postal_code %> / <%= order.address.pref %><%= order.address.city %><%= order.address.address1 %><%= order.address.address2 %></span>
              </p>
              <table>
                <thead>
                  <% order.order_items.each_with_index do |order_item| %>
                    <tr>
                      <td class="orders-product-image">
                        <%= attachment_image_tag order_item.product, :image, :fill, 100, 100, fallback: 'icon-mypage.png', :size => "100x100" %>
                      </td>
                      <td class="orders-product-title-artist-box">
                        <p><label>アルバム/シングル名：</label> <%= order_item.product.album_title %></p>
                        <p><label>アーティスト：</label> <%= order_item.product.artist %></p>
                      </td>
                      <td class="orders-product-quantity-box">
                        <p><label>購入枚数：</label> <%= order_item.quantity %>枚</p>
                      </td>
                      <td class="orders-product-subtotal-box">
                        <p class="orders-product-subtotal"><label>小計：</label>￥<%= order_item.quantity  *  order_item.price %></p>
                      </td>
                    </tr>
                  <% end %>
                </thead>
              </table>
            </div>
          <% end %>
        <% else %>
          <p class="order-nothing-message"><%= @msg2 %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class= fade-in>
	<!-- headerの部分テンプレート -->
<%= render 'layouts/user_header'  %>
	<div class="background-image">
		<div class ="top-contents-box">
			<p><%= image_tag('BeatPlay-logo.png') %></p>

			<%= search_form_for @q do |f| %>
			<div class="search-bar-border">
				<div class="search-bar">
					<%= f.search_field :album_title_or_artist_or_discs_musics_name_cont_any, class: "form-control", style: "background-color:transparent; border:none; color:white; font-size: 15px;" %>
				</div>
				<button class="start-search-button" type="submit"><font color= "white">Search</font></button>
			<% end %>
			</div>
			<div class="start-button-center">
					<%= link_to products_path, class: "start-button" do %>
					Entrance
					<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>
<div></div>