config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admins do
    get 'contacts/index'
    get 'contacts/:id/show' => 'contacts#show', as: 'contact_show'
    get 'contacts/new'
    post 'contacts' => 'contacts#create'

   # get 'users/show'
   #get 'users/index' => 'admins/users#index'
   # get 'users/edit'
   # get 'users/update'
   # delete 'users/destroy'
   post 'users/:id/edit' => 'admins/users#edit', as: 'edit_user'
   resources :users, only:[:show, :index, :edit, :update, :destroy]
   get 'users/search', to: 'users#search', as: 'search_user'
  end

  namespace :admins do
    get 'products/new' => 'products#new', as: 'new_product'
    post 'products/new' => 'products#new', as: 'create_product'
    resources :products, only: [:index, :show, :destroy, :edit]
  end

  namespace :admins do
    get 'orders/index'
    get 'orders/:id/show' => 'orders#show', as: 'order_show'
    patch 'orders/:id/update' => 'orders#update', as: 'order_update'
    patch 'orders/:id/update2' => 'orders#update2', as: 'order_update2'
  end



  resources :users, only: [:edit, :update, :destroy]
  get 'users/top' => 'users#top'
  get 'users/:id/password_confirmation' => 'users#confirm', as: 'confirm_user'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/:id/edit_name' => 'users#edit_name', as: 'edit_name_user'
  get 'users/:id/edit_address' => 'users#edit_address', as: 'edit_address_user'
  get 'users/:id/edit_phonenumber' => 'users#edit_phonenumber', as: 'edit_phonenumber_user'
  get 'users/:id/edit_email' => 'users#edit_email', as: 'edit_email_user'
  get 'users/:id/edit_password' => 'users#edit_password', as: 'edit_password_user'



  #get 'favorites/create'
  #get 'favorites/destroy'
  resources :contacts, only: [:new, :create]
  # get '/contacts/new' => 'contacts#new'
  # post '/contacts/create' => 'contacts#create'


  resources :orders, only: [:new, :show, :create] do
    collection do
      post 'confirm'
      post 'confirm_user'
    end
  end
  # get 'orders/new' => 'orders#new'
  # post 'orders/create_address' => 'orders#create_address'
  # post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  # post 'orders/create' => 'orders#create', as:'create_order'
  # get 'orders/show' => 'orders#show', as: 'show_order'

  #get 'carts/add_cart_item' => 'carts#add_cart_item'
  post '/products/:id/add_cart_items' => 'products#add_cart_item', as: 'add_cart_items'
  get '/products/bpms' => 'products#bpms', as: 'bpms-products'

  resources :carts, only: [:index, :destroy] do
    resource :cart_items, only: [:update]
    resources :cart_items, only: [:destroy]
  end
  # get 'carts/:id' => 'carts#show', as: 'carts_show'
  # delete 'carts/delete_item' => 'carts#delete_item', as: 'delete_cart_item'
  # delete 'carts/delete_all_items' => 'carts#delete_all_items', as: 'delete_all_cart_items'

  #get 'products/index'
  #get 'products/show'
  patch 'products/:id/update' => 'products#update', as: 'update_product'
  resources :products, only: [:index, :show] do
    resource :favorites, only:[:create, :destroy]
  end

  get 'admins/top' => 'admins/users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resourses :contacts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_paranoid

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at? super: :deleted_account
  end

# gem jp_prefectureの追加の為、追記しました------------------------------------------------
  include JpPrefecture
  jp_prefecture :pref

    def prefecture_name
      JpPrefecture::Prefecture.find(code: pref_id).try(:name)
    end

    def prefecture_name=(prefecture_name)
      self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture_name).code
    end

# ----------------------------------------------------------------------------------

  has_many :orders
  has_many :addresses
  has_one :cart
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :orders, :allow_destroy => true
  has_many :order_items, through: :orders  #ユーザーマイページの購入履歴表示に必要

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,
  	presence:true,
  	length: { minimum: 1, maximum: 20}

  validates :last_name,
  	presence:true,
  	length: { minimum: 1, maximum: 20}

  validates :kana_first,
  	presence:true,
    format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  validates :kana_last,
  	presence:true,
    format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  validates :postal_code,
  	presence:true

  validates :pref,
  	presence:true

  validates :city,
  	presence:true

  validates :phone_number,
  	presence:true,
    format: { with: /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/,
            message: 'は正しい電話番号で入力して下さい。 例：◯◯◯-◯◯◯◯-◯◯◯◯ 、「ー」は無しでも可' }
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @o_counter = Order.count
    @u_counter = User.count
    @p_counter = Product.count
    # 注文直近１０件をひっぱってくる記述

    @q = Order.ransack(params[:q])
    @orders2 = @q.result.last(10)
    if @q == nil
      @msg = "現在注文はありません"
    end
    # ユーザー直近１０件の登録者を表示
    @q2 = User.ransack(params[:q])
    @users2 = @q2.result.last(10)
    if @users2 == nil
      @msg2 = "現在登録ユーザーはいません"
    end
    # binding.pry
    # @admin = Admin.find(params[:id])
  end

  def index
    @users2 = User.all
    @users = User.with_deleted.page(params[:page]).per(30)
    @admins = Admin.all

    @q = User.ransack(params[:q])
    @searchuser = @q.result
    @q2 = User.with_deleted.ransack(params[:q])
    @searchuser2 = @q2.result
  end

  def search
    @q = User.search(search_params)
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.with_deleted.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '登録情報を更新しました！'
      redirect_to admins_user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.soft_delete
      flash[:success] = 'ユーザーを削除しました(soft_deleted)'
      render 'index'
    end
  end

private
  def user_params
    params.require(:user).permit(:first_name,
                                  :last_name,
                                  :kana_first,
                                  :kana_last,
                                  :postal_code,
                                  :pref,
                                  :city,
                                  :address1,
                                  :address2,
                                  :phone_number,
                                  :email,
                                  :password)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected
  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |user|
    end
    @cart = Cart.new
    if current_user
       @cart.user_id = current_user.id
       @cart.save
    end
  end

  # GET /resource/edit
  def edit
    #super do
    #end
    @user = current_user
    @orders = @user.orders.find_by(status: '0')
    @orders2 = @user.orders.find_by(status: '1')
  end

  # PUT /resource
  # def update
    # super
    # end
    # @user = current_user
    # if @user.id == current_user.id
    #     # redirect_to edit_user_password_path(current_user)
    #   # redirect_to edit_user_path(current_user)

    #   render :edit_password
    # else
    #   redirect_to edit_user_path(current_user)
    # end
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    edit_user_path(current_user)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top]

  def top
    @users = User.last(10)
    @orders = Order.last(10)
    @q = Product.includes(:discs,:musics).ransack(params[:q])
  end

  def confirm
  end

  def mypage
    @user = User.find(params[:id])
    @favorites = @user.favorites.reverse_order
    @q = Product.includes(:discs,:musics).ransack(params[:q])
    @q2 = Music.ransack(params[:q])
    @msg = 'お気に入りリストに商品は入っておりません。'
    @msg2 = '購入履歴はございません。'
  end

  def edit
    @q = Product.includes(:discs,:musics).ransack(params[:q])
    @q2 = Music.ransack(params[:q])
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_name
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_name
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_address
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_address
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_phonenumber
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_phonenumber
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_email
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit_email
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def edit_password
    # @user = User.find(params[:id])
    @user = current_user
    if @user.id == current_user.id
      # redirect_to edit_password_user_path(current_user)
      # render :edit_password
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'successfully updated'
      redirect_to edit_user_path(@user.id)
    else
      redirect_to edit_user_path(@user.id)
    end
  end

  def destroy
    @user = current_user
    @user.soft_delete
    sign_out(@user)
  end

  private
    def user_params
      params.require(:user).permit(:email,:encrypted_password,:first_name,:last_name,:kana_first,:kana_last,:postal_code,:pref,:city,:address1,:address2,:phone_number)
    end


end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/_header.html.erb
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top headline">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarEexample8">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">
            <%= link_to users_top_path do %>
            <span><%= image_tag('BeatPlay-logo.png', class: "logo") %></span>
           <% end %>
          </div>
          <span id="RealtimeClock"><%= Date.current.strftime('%Y/%m/%d.%a') %></span>
        </div>

        <div class="collapse navbar-collapse" id="navbarEexample8">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to admins_top_path do %>
              <i class="fas fa-chalkboard-teacher"></i>TOP<% end %>
            </li>
            <li><%= link_to admins_products_path do %>
              <i class="fas fa-compact-disc"></i>CD<% end %>
            </li>
            <li><%= link_to admins_orders_index_path do %>
              <i class="fa fa-clipboard" aria-hidden="true"></i>ORDER<% end %>
            </li>
            <li><%= link_to admins_users_path do %>
              <i class="fa fa-address-card" aria-hidden="true"></i>USER<% end %>
            </li>
            <li><%= link_to "#" do %>
              <i class="fa fa-comments" aria-hidden="true"></i>CONTACT<% end %>
            </li>
            <li><%= link_to destroy_admin_session_path, method: :delete, data:{ confirm:"ログアウトしてよろしいですか？", cancel:"Cancel", commit:"OK" } do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true">LOGOUT</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</header>

app/views/admins/users/edit.html.erb
<%= render 'admins/users/header'  %>

<div class="ad-box">
  <div class="ad-index-box">
  	<div class="ad-index-inner">
  		<div class="ad-tbl-title">ユーザー情報編集</div>
  		  <%= form_for(@user, url: admins_user_path(@user), method: :put) do |f| %>
        <div class="form-horizontal">

          <div class="form-group">
            <label class="col-sm-3 control-label">名前：</label>
              <div class="col-sm-8">
                <%= f.text_field :first_name, autofocus: true %><%= f.text_field :last_name %><br>
                <%= f.text_field :kana_first %><%= f.text_field :kana_last %>
              </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">郵便番号：</label>
              <div class="col-sm-8">
                <%= f.text_field :postal_code %>
              </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">住所：</label>
              <div class="col-sm-8">
                <%= f.collection_select :pref, JpPrefecture::Prefecture.all, :name, :name %>  <%= f.text_field :city %>
                <%= f.text_field :address1 %><%= f.text_field :address2 %>
              </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">電話番号：</label>
              <div class="col-sm-8">
                <%= f.text_field :phone_number %>
              </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">メール：</label>
              <div class="col-sm-8">
                <%= f.email_field :email, autocomplete: "email" %>
              </div>
          </div>

          <div class="actions ad-submit-btn">
            <%= f.submit "更新", class: "btn btn-default btn-ms" %>
          </div>
      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<%= render 'admins/users/header'  %>

<div class="ad-box">
  <div class="ad-page">
    <div class="ad-user-index-box">
      <div class="ad-user-ind-box">
        <table class="table table-hover">
          <div class="ad-tbl-title2">登録ユーザー一覧</div>
           <thead>
            <tr>
              <th><input type="checkbox"></th>
              <th><%= sort_link(@q, :id, "ID") %></th>
              <th><%= sort_link(@q, :first_name, "ユーザー名") %></th>
              <th><%= sort_link(@q, :emali, "Email") %></th>
              <th><%= sort_link(@q, :created_at, "登録日") %></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

        <% if @users2.count == @searchuser.count %>

          <tbody>
            <% @users.each do |user| %>
                <tr>
                  <td><input type="checkbox"></td>
                  <td><%= user.id %></td>
                  <td>
                    <% if user.deleted_at != nil %>
                      <%= user.first_name %><%= user.last_name %>**
                    <% else %>
                      <%= user.first_name %><%= user.last_name %>
                    <% end %>
                  </td>
                  <td><%= user.email %></td>
                  <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
                  <td><%= button_to "詳細", admins_user_path(user.id), method: :get, class: "btn btn-default btn-ms" %></td>
                  <td><%= button_to "編集", edit_admins_user_path(user.id), method: :get, class: "btn btn-default btn-ms" %></td>
                  <td>
                    <%= button_to "削除", admins_user_path(user.id), method: :delete, class: "btn btn-default btn-ms", data: { confirm: '削除します。よろしいですか？' }%>
                  </td>
                </tr>
            <% end %>
          </tbody>

        <% else %>

          <tbody>
            <% @searchuser2.each do |user| %>
            <tr>
              <td><input type="checkbox"></td>
              <td><%= user.id %></td>
              <td><%= user.first_name %><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= button_to "詳細", admins_user_path(user.id), method: :get, class: "btn btn-default btn-ms" %></td>
              <td><%= button_to "編集", edit_admins_user_path(user.id), method: :get, class: "btn btn-default btn-ms" %></td>
              <td>
                <%= button_to "削除", admins_user_path(user.id), method: :delete, class: "btn btn-default btn-ms", data: { confirm: '削除します。よろしいですか？' }%>
              </td>
            </tr>
            <% end %>
          </tbody>
        <% end %>
        <div class="ad-user-notice">※名前の脇に「**」がついているユーザーは退会済みです</div>

        </table>
      </div>


      <div class="ad-ad-index-box">
        <div class="box-for-position2">
          <h4 class="ad-index">管理者情報</h4>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>名前</th>
                  <th>Email</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @admins.each do |ad| %>
                <tr>
                  <td><%= ad.name %></td>
                  <td><%= ad.email %></td>
                  <td>
                    <%= button_to "編集", edit_admin_registration_path, method: :get, class: "btn btn-default btn-xs" %>
                  </td>
                  <td>
                    <%= button_to "削除", admin_registration_path, method: :delete, class: "btn btn-default btn-xs", data: { confirm: '削除します。よろしいですか?' }%>
                  </td>
                  <td>
                    <%= button_to '追加', destroy_admin_session_path, method: :delete, class: "btn btn-default btn-xs" %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>

            <div class="extraction-box">
              <div class="box-for-position">
                <div class="ad-search-box">
                  <%= search_form_for @q, url:admins_users_path, method: :get do |f| %>
                    <%= f.search_field :id_eq %>
                    <%= f.submit "ID検索" %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/admins/users/show.html.erb
<%= render 'admins/users/header'  %>

<div class="ad-box">
  <div class="ad-user-show-box">
    <div class="ad-user-show-inner">
      <div class="ad-user-info">
        <div class="ad-tbl-title2">ユーザー登録情報</div>
          <div class="ad-form">
            <div class="ad-user-notice">※名前の脇に「**」がついているユーザーは退会済みです</div>
            <p class="form-control-static">
              <label>名前：</label>
                <% if @user.deleted_at != nil %>
                  <%= @user.first_name %><%= @user.last_name %>**
                <% else %>
                  <%= @user.first_name %><%= @user.last_name %>
                <% end %>
            </p>
          </div>
          <div class="ad-form">
            <p class="form-control-static">
              <label>住所：</label>
                <%= @user.postal_code %><br/>
                <%= @user.pref %> <%= @user.city %>
                <%= @user.address1 %> <%= @user.address2 %>
            </p>
          </div>
          <div class="ad-form">
              <p class="form-control-static">
                <label>電話番号：</label>
                <%= @user.phone_number %>
              </p>
          </div>
          <div class="ad-form">
              <p class="form-control-static">
                <label>メール：</label>
                <%= @user.email %>
                </p>
          </div>
          <div class="ad-form">
            <div class="ad-user-btn-box">
              <%= button_to "編集", edit_admins_user_path(@user.id), method: :get, class: "btn btn-default btn-ms" %> <%= button_to "削除", user_registration_path(@user.id), class:"btn btn-default btn-ms", data: { confirm: 'Are you sure?' }, method: :delete %>
            </div>
          </div>
      </div>
    </div>

    <div class="ad-user-orders">
      <div class="ad-user-orders-inner">
        <div class="ad-tbl-title2">オーダー履歴</div>
        <table class="table">
            <thead>
              <tr>
                <th>オーダーNo.</th>
                <th>ステータス</th>
                <th>購入日</th>
                <th>合計</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% @user.orders.reverse_each do |order| %>
                <td><%= link_to order.id, admins_order_show_path(order.id) %></td>
                <td><%= order.status %></td>
                <td><%= order.created_at %></td>
                <td><%= order.total %></td>
              </tr>
              <% end %>
            </tbody>
        </table>
    </div>

  </div>
</div>

app/views/admins/users/top.html.erb
<%= render 'admins/users/header'  %>
<div class="ad-box">
	<div class="counter-box">
		<ul class="ad-counter">
			<li>登録ユーザー合計: <b><%= @u_counter %></b> 人 </li>
			<li>総オーダー数: <b><%= @o_counter %></b> 件 </li>
			<li>商品ラインナップ: <b><%= @p_counter %></b> 点 </li>
		</ul>
	</div>

	<div class="dashboard-main-box">
			<div class="dashboard-box">
				<p class="dashboard-sub">最新のオーダー</p>
					<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th>購入確定日</th>
									<th>オーダーNo.</th>
									<th>ステータス</th>
								</tr>
							</thead>
							<tbody>
								<!-- each start -->
								<% @orders2.reverse.each do |order| %>
									<tr>
										<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
										<td>#<%= order.id %>-<%= order.created_at.strftime('%Y%m%d') %></td>
										<td><%= order.status %></td>
									</tr>
								<% end %>
								<!-- each end -->
							</tbody>
					</table>
					 <p align="center"><%= @msg %></p>
			</div>
			<div class="dashboard-box">
				<p class="dashboard-sub">最新の登録ユーザー</p>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>ユーザーID</th>
							<th>Email</th>
							<th>登録日</th>
						</tr>
					</thead>
					<tbody>
						<!-- each start -->
					<% @users2.reverse_each do |user| %>
						<tr>
							<td><%= user.id %></td>
							<td>
								<%= link_to admins_user_path(user) do %>
									<%= user.email %>
								<% end %>
							</td>
							<td><%= user.created_at.strftime('%Y/%m/%d') %></td>
						</tr>
					<% end %>
						<!-- each end -->
					</tbody>
				</table>
				<p align="center"><%= @msg2 %></p>
			</div>
			</div>
	</div>
</div>