config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admins do
    get 'contacts/index'
    get 'contacts/:id/show' => 'contacts#show', as: 'contact_show'
    get 'contacts/new'
    post 'contacts' => 'contacts#create'

   # get 'users/show'
   #get 'users/index' => 'admins/users#index'
   # get 'users/edit'
   # get 'users/update'
   # delete 'users/destroy'
   post 'users/:id/edit' => 'admins/users#edit', as: 'edit_user'
   resources :users, only:[:show, :index, :edit, :update, :destroy]
   get 'users/search', to: 'users#search', as: 'search_user'
  end

  namespace :admins do
    get 'products/new' => 'products#new', as: 'new_product'
    post 'products/new' => 'products#new', as: 'create_product'
    resources :products, only: [:index, :show, :destroy, :edit]
  end

  namespace :admins do
    get 'orders/index'
    get 'orders/:id/show' => 'orders#show', as: 'order_show'
    patch 'orders/:id/update' => 'orders#update', as: 'order_update'
    patch 'orders/:id/update2' => 'orders#update2', as: 'order_update2'
  end



  resources :users, only: [:edit, :update, :destroy]
  get 'users/top' => 'users#top'
  get 'users/:id/password_confirmation' => 'users#confirm', as: 'confirm_user'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/:id/edit_name' => 'users#edit_name', as: 'edit_name_user'
  get 'users/:id/edit_address' => 'users#edit_address', as: 'edit_address_user'
  get 'users/:id/edit_phonenumber' => 'users#edit_phonenumber', as: 'edit_phonenumber_user'
  get 'users/:id/edit_email' => 'users#edit_email', as: 'edit_email_user'
  get 'users/:id/edit_password' => 'users#edit_password', as: 'edit_password_user'



  #get 'favorites/create'
  #get 'favorites/destroy'
  resources :contacts, only: [:new, :create]
  # get '/contacts/new' => 'contacts#new'
  # post '/contacts/create' => 'contacts#create'


  resources :orders, only: [:new, :show, :create] do
    collection do
      post 'confirm'
      post 'confirm_user'
    end
  end
  # get 'orders/new' => 'orders#new'
  # post 'orders/create_address' => 'orders#create_address'
  # post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  # post 'orders/create' => 'orders#create', as:'create_order'
  # get 'orders/show' => 'orders#show', as: 'show_order'

  #get 'carts/add_cart_item' => 'carts#add_cart_item'
  post '/products/:id/add_cart_items' => 'products#add_cart_item', as: 'add_cart_items'
  get '/products/bpms' => 'products#bpms', as: 'bpms-products'

  resources :carts, only: [:index, :destroy] do
    resource :cart_items, only: [:update]
    resources :cart_items, only: [:destroy]
  end
  # get 'carts/:id' => 'carts#show', as: 'carts_show'
  # delete 'carts/delete_item' => 'carts#delete_item', as: 'delete_cart_item'
  # delete 'carts/delete_all_items' => 'carts#delete_all_items', as: 'delete_all_cart_items'

  #get 'products/index'
  #get 'products/show'
  patch 'products/:id/update' => 'products#update', as: 'update_product'
  resources :products, only: [:index, :show] do
    resource :favorites, only:[:create, :destroy]
  end

  get 'admins/top' => 'admins/users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resourses :contacts
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!
    # before_action :setup_cart_item!, only: [:index, :destroy]

  def index
    @q = Product.includes(:discs,:musics).ransack(params[:q])
    @q2 = Music.ransack(params[:q])
    @cart = Cart.find_by(user_id: current_user)
    @cart_item = CartItem.find_by(cart_id: @cart.id)
    if @cart_item == nil
      @trigger_numb = 1
      @user = current_user
    else
      @trigger_numb = 2
      @user = current_user
      @cart_items = @cart.cart_items
      # binding.pry
      @cart_item.subtotal = @cart_item.product.price * @cart_item.quantity

      @total = 0 #初期化
      @cart_items.each do |cart_item|
        @total = @total + cart_item.subtotal.to_i
      end
    end
  end

  # カート内商品を全て削除
  def destroy
    @cart_items = CartItem.all
    @cart_items.each do |cart_item|
      cart_item.destroy
    end
    redirect_to carts_path
  end

    # private

    # def setup_cart_item!
    #   @cart_item = current_cart.cart_items.find_by(product_id[:product_id])
    # end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add_cart_item.html.erb
<h1>Carts#add_cart_item</h1>
<p>Find me in app/views/carts/add_cart_item.html.erb</p>

app/views/carts/checkout.html.erb
<h1>Carts#checkout</h1>
<p>Find me in app/views/carts/checkout.html.erb</p>

app/views/carts/delete_all_items.html.erb
<h1>Carts#delete_all_items</h1>
<p>Find me in app/views/carts/delete_all_items.html.erb</p>

app/views/carts/delete_item.html.erb
<h1>Carts#delete_item</h1>
<p>Find me in app/views/carts/delete_item.html.erb</p>

app/views/carts/index.html.erb
<head>
		<title>カート内商品一覧</title>
</head>
<!-- headerの部分テンプレート -->
<%= render 'layouts/user_header'  %>
<section>
		<!-- 検索フォーム -->
	<%= render 'products/list', q: @q, q2: @q2 %>
			<% if @trigger_numb == 1 %>
			<div class="user-inverse">
				<div class = "blank-box">
					<div style="padding-top:10px;">
						<font size="8">Blank!</font>
					</div>
					<div class="cart-blank">
						<%= image_tag('blank_cart.png', size: "350x250") %>
					</div>
				</div>
			</div>
			<% else @trigger_numb == 2 %>
				<div class="main-box user-inverse">
					<div class="cart-item-box">
						<table class="cartlist">
							<thead>
								<% price_sum = 0 %>
							<!-- ここからeach do -->
								<% @cart_items.each do |cart_item| %>
								<tr>
									<td class="p-img">
										<%= link_to product_path(cart_item.product) do %>
											<%= attachment_image_tag cart_item.product, :image, :fill, 250, 250, fallback: 'icon-mypage.png', :size => "250x250", class: "p-img" %>
										<% end %>
									</td>
									<td class="p-info">
										<%= link_to product_path(cart_item.product) do %>
											<div>
												<p><%= cart_item.product.album_title %></p>
											</div>
											<div>
												<p><%= cart_item.product.artist %></p>
											</div>
										<% end %>
									</td>
									<td class="p-price"><p>¥ <%= cart_item.product.price %> </p></td>
									<td class="p-qty">
										<%= form_for cart_item, url: cart_cart_items_path(cart_item), method: :patch  do |f| %>
										<div align="center" style="margin-top:20px; background-color:rgba(200, 200, 200, 0.3); border-radius:15px; padding:10px;">
											<% if cart_item.product.stock > 0 %>
												<%= f.number_field :quantity, default: cart_item.quantity, min: 1, max: cart_item.product.stock, class: "form-control", style: "border-radius:30px;" %>
												<%= f.submit "更新", class: "btn btn-default btn-xs", style:"margin-top:10px;" %>
											<% else %>
												<p class="alert-zero">在庫なし</p>
											<% end %>
										</div>
										<% end %>
									</td>
									<td class="p-subtotal">
										<p>¥ <%= cart_item.product.price * cart_item.quantity %></p>
										<% price_sum =  price_sum + cart_item.product.price * cart_item.quantity %>
									</td>
										<td class="p-button">
										<%= link_to cart_cart_item_path(@cart, cart_item), method: :delete, data:{confirm: "カートから商品を削除します。よろしいですか？"} do %>
											 <p><button class="btn btn-danger btn-xs">削除</button></p>
										<% end %>
									</td>
								</tr>
								<% end %>
								<!-- ここまでeach do -->
							</thead>
						</table>
						<div class="row cash-button">
								<div class="col-lg-4"></div>
								<div class="col-lg-3" align="right">
								<font size="6">合計¥ <%= price_sum %></font>
								</div>
								<%= link_to new_order_path do%>
									<button style="border-radius:30px; margin-right:5px;" class="col-lg-2 btn btn-info btn-ms">購入手続き（送付先選択へ）</button>
								<% end %>
								<%= link_to cart_path(@cart), method: :delete, data:{ confirm: "カート内の商品を全て削除します。よろしいですか？"} do %>
									<button style="border-radius:30px;" class="col-lg-2 btn btn-default btn-ms">カートを空にする</button>
								<% end %>
								<p class="col-lg-1"></p>
						</div>
					<% end %>
				</div>
		</div>
</section>

app/views/carts/show.html.erb
<h1>#indexへ引っ越しました。パスまたはルーティングを確認してください。</h1>